# Generated by Django 3.1.5 on 2021-03-30 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('create_date', models.DateField(default=datetime.date.today, verbose_name='First Published')),
                ('maintext', models.TextField(blank=True, verbose_name='Post Content')),
            ],
        ),
        migrations.AlterField(
            model_name='page',
            name='update_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Last Updated'),
        ),
    ]
