# Generated by Django 3.1.5 on 2021-04-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='maintext',
            field=models.TextField(verbose_name='Post Content'),
        ),
    ]
