# Generated by Django 3.1.5 on 2021-04-04 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210403_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='create_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='First Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Date Published'),
        ),
    ]
