# Generated by Django 3.1.5 on 2021-04-05 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210404_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='First Published'),
        ),
        migrations.AlterField(
            model_name='page',
            name='update_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
