# Generated by Django 3.1.5 on 2021-04-05 19:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210405_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='maintext',
            field=ckeditor.fields.RichTextField(verbose_name='Post Content'),
        ),
    ]
